[tool.black]
line-length = 120
target-version = ['py39']
include = '\.py$'
force-exclude = '''
 (
     .idea
     | .pytest_cache
     | .mypy_cache
     | .ruff_cache
     | venv
     | node_modules
     | .*/migrations/
 )
'''